# azure-pipeline.yml (updated)
trigger:
  - main

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'  # Lowercase 'b'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NuGetAuthenticate@1
      displayName: 'NuGet Authenticate'
    
    - task: UseDotNet@2
      inputs:
        version: '8.x'
        includePreviewVersions: false
        
    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet'

    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        command: 'restore'
        restoreSolution: '$(solution)'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'

    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(solution)'
        arguments: '--configuration $(buildConfiguration)'  # Lowercase 'b'

    # Clean the publish directory
    - task: DeleteFiles@1
      displayName: 'Clean publish directory'
      inputs:
        SourceFolder: '$(Build.ArtifactStagingDirectory)'
        Contents: '**/*'

    # Publish Function App
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/DopamineDetoxFunction.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: DeployToTest
  dependsOn: Build
  condition: succeeded()
  variables:
    - group: SMD-Test-Variables
  jobs:
  - deployment: Deploy
    environment: 'test'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureCLI@2
            displayName: 'Clean existing deployment'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              scriptType: 'bash'
              inlineScript: |
                  az functionapp deployment list --name smd-function-test --resource-group social-media-detox --output table
                  az functionapp deployment source config-zip delete --name smd-function-test --resource-group social-media-detox

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'SMD-KeyVault'
              KeyVaultName: 'test-key-vault-v2'
              SecretsFilter: 'SMD--AzureSignalRConnectionString,SMD--YouTubeApiKey,ProjectDb--SQL-DefaultConnectionString'
              RunAsPreJob: false

          - task: AzureAppServiceManage@0
            displayName: 'Stop Function App'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              Action: 'Stop Azure App Service'
              WebAppName: 'smd-function-test'
              SpecifySlotOrASE: false

          - task: AzureFunctionApp@2
            displayName: 'Deploy Function App'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appType: 'functionApp'
              appName: 'smd-function-test'
              package: '$(Pipeline.Workspace)/drop/*.zip'
              deploymentMethod: 'zipDeploy'
              resourceGroupName: 'social-media-detox'

          - task: AzureCLI@2
            displayName: 'Start Function App and Configure Settings'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Configure app settings
                az functionapp config appsettings set --name 'smd-function-test' --resource-group 'social-media-detox' --settings \
                  "FUNCTIONS_WORKER_RUNTIME=dotnet-isolated" \
                  "DOTNET_ISOLATED_RUNTIME_VERSION=8.0" \
                  "FUNCTIONS_EXTENSION_VERSION=~4" \
                  "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED=1" \
                  "WEBSITE_RUN_FROM_PACKAGE=1" \
                  "DopamineDetox:BaseUrl=$(DopamineDetox:BaseUrl)" \
                  "DopamineDetox:TimeoutSeconds=30" \
                  "DopamineDetox:MaxRetryAttempts=3" \
                  "DopamineDetox:RetryDelayMilliseconds=1000" \
                  "SearchApiUrl=$(SearchApiUrl)" \
                  "YouTubeApiKey=$(SMD--YouTubeApiKey)" \
                  "AzureSignalRConnectionString=$(SMD--AzureSignalRConnectionString)" \
                  "XOEmbedApiUrl=https://publish.twitter.com/oembed?url=" \
                  "XLoginUrl=https://x.com/i/flow/login" \
                  "YouTubeBaseUrl=https://www.googleapis.com/youtube/v3/" \
                  "ConnectionStrings__DefaultConnection"="$(ProjectDb--SQL-DefaultConnectionString)" \

                # Start the function app
                az functionapp start --name 'smd-function-test' --resource-group 'social-media-detox'

- stage: DeployToProduction
  dependsOn: DeployToTest
  condition: succeeded()
  variables:
    - group: SMD-Prod-Variables
  jobs:
  - deployment: Deploy
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Clean existing deployment'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              scriptType: 'bash'
              inlineScript: |
                  az functionapp deployment list --name smd-function-prod --resource-group social-media-detox --output table
                  az functionapp deployment source config-zip delete --name smd-function-prod --resource-group social-media-detox

          - task: AzureKeyVault@2
            inputs:
              azureSubscription: 'SMD-KeyVault'
              KeyVaultName: 'prod-key-vault-v1'
              SecretsFilter: 'SMD--AzureSignalRConnectionString,SMD--YouTubeApiKey,ProjectDb--SQL-DefaultConnectionString'
              RunAsPreJob: false

          - task: AzureAppServiceManage@0
            displayName: 'Stop Function App'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              Action: 'Stop Azure App Service'
              WebAppName: 'smd-function-prod'
              SpecifySlotOrASE: false

          - task: AzureFunctionApp@2
            displayName: 'Deploy Function App'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              appType: 'functionApp'
              appName: 'smd-function-prod'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'zipDeploy'
              resourceGroupName: 'social-media-detox'

          - task: AzureCLI@2
            displayName: 'Start Function App and Configure Settings'
            inputs:
              azureSubscription: 'SocialMediaDetoxConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Configure app settings
                az functionapp config appsettings set --name 'smd-function-prod' --resource-group 'social-media-detox' --settings \
                  "FUNCTIONS_WORKER_RUNTIME=dotnet-isolated" \
                  "DOTNET_ISOLATED_RUNTIME_VERSION=8.0" \
                  "FUNCTIONS_EXTENSION_VERSION=~4" \
                  "WEBSITE_USE_PLACEHOLDER_DOTNETISOLATED=1" \
                  "WEBSITE_RUN_FROM_PACKAGE=1" \
                  "DopamineDetox:BaseUrl=$(DopamineDetox:BaseUrl)" \
                  "DopamineDetox:TimeoutSeconds=30" \
                  "DopamineDetox:MaxRetryAttempts=3" \
                  "DopamineDetox:RetryDelayMilliseconds=1000" \
                  "SearchApiUrl=$(SearchApiUrl)" \
                  "YouTubeApiKey=$(SMD--YouTubeApiKey)" \
                  "AzureSignalRConnectionString=$(SMD--AzureSignalRConnectionString)" \
                  "XOEmbedApiUrl=https://publish.twitter.com/oembed?url=" \
                  "XLoginUrl=https://x.com/i/flow/login" \
                  "YouTubeBaseUrl=https://www.googleapis.com/youtube/v3/" \
                  "ConnectionStrings__DefaultConnection"="$(ProjectDb--SQL-DefaultConnectionString)" \

                # Start the function app
                az functionapp start --name 'smd-function-prod' --resource-group 'social-media-detox'